sudo: required
services:
    - docker
language: node_js
env:
    global:
      - secure: msq40VzYVlpUJ0E4gB7nUnGtVGjrFNznv6c/Eje6tUAEdse+d9lrZahZ67LCiXqu3VneIRiKAJNppnC2fetyK0YtHjPZQthCmnEACLKfm6Uy9cdtGGjf1N/RsKnHMSrcYukU1Nf2jBJdTeURzG6+ASUBVmoI0Dmz1i7P+D32jsfyC2qXoi8R+rnAHbkZoAgsjmCZuLtgoeC+9Ayf0kFPtW7oDmPd6dBUVASLz9Awvxku0yFiyX4kFWZ7yRQpNI69vd83colZfAa+8P5B4PXBssKHS4+ZCxs1/7j+2tuMIU703SGp85tlORJFMd8Us0SOqIhSNM6TwbgY1MhgGliHTBJ7iJjn1YZEGJRdk19WRFdi6VmdG3Uks4aCRuv4uHJ+UzyUL635rJPU9rNYOH7M6A1CYmk762okKcURvMFgPZ4+tmmGofMmrPg3npSSldBMd/PZr6I7FXjeIpUs+qmhs6gY5HZW6/Rta3RkkMrawWZtDyVDW9XPwxkBOfHholHz42CCBbuiOeapbZMVFnEU6/ojj+kZDgeHQBklMVbnpRdK832eepls3yT8TvdoGwXukV/jucIFietfmavbtxoF+uqYWe3IyTOPOFyHYtL+nhZN2NwlGP+m0T2WcGJcsJ3oKFEyVnCZOZqFnSG/8ayeoDqrsCBzx6k+HBQA5O1y/8U=
      - REGISTRY_USER=kevinxin1990
node_js:
    - stable
cache:
directories:
    - node_modules
before_script:
    - npm install
    - docker pull biothings/bte_reasoner_api || true
script:
    - npm test
    - npm run coveralls
    - docker build --pull -cache-from biothings/bte_reasoner_api --tag biothings/bte_reasoner_api .
    - docker run -d biothings/bte_reasoner_api

after_script:
    - docker images

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
    provider: script
    script: docker push biothings/bte_reasoner_api
    on:
        branch: master

