---
services:
  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ulimits:
      memlock: -1
    ports: [6379:6379]
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    network_mode: host
  mongodb:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    # environment: [MONGO_INITDB_ROOT_USERNAME=user, MONGO_INITDB_ROOT_PASSWORD=pass]
    ports: [27017:27017]
  retriever:
    container_name: retriever
    image: biopack-team/retriever
    restart: on-failure
    build: .
    ports: [8080:8080]
    depends_on: [mongodb, dragonfly]
    environment:
      MONGO__HOST: host.docker.internal
      REDIS__HOST: host.docker.internal
