---
services:
  dragonfly:
    container_name: dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    ulimits:
      memlock: -1
    ports: [6888:6379]
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: host
  mongodb:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    # environment: [MONGO_INITDB_ROOT_USERNAME=user, MONGO_INITDB_ROOT_PASSWORD=pass]
    ports: [27017:27017]
  retriever:
    container_name: retriever
    image: biopack-team/retriever
    restart: on-failure
    build: .
    ports: [8080:8080]
    depends_on: [mongodb, dragonfly]
    # network_mode: host
    environment:
      MONGO__HOST: mongodb
      REDIS__HOST: dragonfly
      REDIS__PORT: 6379
#     secrets:
#       - tier0__neo4j__host
#       - tier0__neo4j__username
#       - tier0__neo4j__password
# secrets:
#   tier0__neo4j__host:
#     file: config/secrets/tier0__neo4j__host
#   tier0__neo4j__username:
#     file: config/secrets/tier0__neo4j__username
#   tier0__neo4j__password:
#     file: config/secrets/tier0__neo4j__password
