version: '3'
services:
  retriever:
    container_name: retriever
    restart: on-failure
    build: .
    image: BioPack-team/retriever
    ports:
      - '3000:3000'
    env_file: .compose-env
  redis:
    container_name: retriever-redis
    restart: on-failure
    image: "redis:alpine"
    volumes:
      - ./.redis.conf:/usr/local/etc/redis/redis.conf
