version: '3'
services:
  bte:
    container_name: bte
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG: biomedical-id-resolver,bte*
      DEBUG_COLORS: true
    # volumes:
    #   - /log/bte:/home/node/app/log
  redis:
    container_name: bte_redis
    restart: always
    image: "redis:alpine"
    volumes:
      - ./.redis.conf:/usr/local/etc/redis/redis.conf
