from typing import Literal, cast

import pytest
from payload.cases import (  # pyright:ignore[reportImplicitRelativeImport]
    Q_GRAPH_CASES,
    Q_GRAPH_CASES_IDS,
)
from payload.es_hits import (  # pyright:ignore[reportImplicitRelativeImport]
    SIMPLE_ES_HITS,
)
from payload.trapi_qgraphs import (  # pyright:ignore[reportImplicitRelativeImport]
    BASE_QGRAPH, EXPANDED_QUALIFIER_QGRAPH, ID_BYPASS_PAYLOAD,
    SINGLE_EXPANDED_QUALIFIER_QGRAPH,
)

from retriever.data_tiers.tier_1.elasticsearch.constraints.types.qualifier_types import (
    ESBoolQueryForExpandedQualifiers,
    ESEquivalentQualifierPairCollection,
    ESTermClause,
)
from retriever.data_tiers.tier_1.elasticsearch.transpiler import (
    EDGE_FIELDS_MAPPING,
    NODE_FIELDS_MAPPING,
    ElasticsearchTranspiler,
)
from retriever.data_tiers.tier_1.elasticsearch.types import ESPayload
from retriever.types.trapi import QualifierConstraintDict, QualifierDict, QueryGraphDict, QNodeDict
from retriever.utils import biolink

# sample generated query


@pytest.fixture
def es_transpiler() -> ElasticsearchTranspiler:
    return ElasticsearchTranspiler()


def _convert_triple(
    es_transpiler: ElasticsearchTranspiler,
    qgraph: QueryGraphDict,
) -> ESPayload:
    """Wrapper for convert_triple so attribute constraints are generated by default."""
    edge = next(iter(qgraph["edges"].values()), None)
    if edge is None:
        raise ValueError("Query graph must contain exactly one edge.")
    in_node = qgraph["nodes"][edge["subject"]]
    out_node = qgraph["nodes"][edge["object"]]
    return es_transpiler.generate_queries(in_node, edge, out_node, gen_attribute_constraints=True)


def _convert_batch_triple(
    es_transpiler: ElasticsearchTranspiler,
    qgraphs: list[QueryGraphDict]
) -> list[ESPayload]:
    return [_convert_triple(es_transpiler, qgraph) for qgraph in qgraphs]


def check_list_fields(reference: list, against: list):
    for ref, ag in zip(reference, against):
        if ref.startswith("biolink:"):
            assert ref[8:] == ag
        else:
            assert ref == ag


def remove_biolink_prefixes(input: list):
    return list(map(biolink.rmprefix, input))


def verify_expanded_qualifier(
    qualifier: QualifierDict,
    generated_query: ESEquivalentQualifierPairCollection,
):
    """Verify a single qualifier's `bool.should` expansion.

    The original (type, value) pair must appear among the should terms (along
    with any biolink descendants).
    """
    assert "bool" in generated_query
    inner = generated_query["bool"]
    assert "should" in inner
    assert inner.get("minimum_should_match") == 1

    should_terms: list[ESTermClause] = inner["should"]
    assert len(should_terms) >= 1

    qtype = biolink.rmprefix(qualifier["qualifier_type_id"])
    qvalue = biolink.rmprefix(qualifier["qualifier_value"])
    pairs = {(k, v) for term in should_terms for k, v in term["term"].items()}
    # every term in this should-array must be for the same qualifier type
    assert {t for t, _ in pairs} == {qtype}
    # and the original value must be retained alongside any descendants
    assert qvalue in {v for _, v in pairs}


def verify_expanded_multi_qualifiers(
    qualifiers: list[QualifierDict],
    generated_query: ESBoolQueryForExpandedQualifiers,
):
    """Verify a multi-qualifier constraint's `bool.must` expansion.

    Each qualifier in the input set becomes one `bool.should` entry within the
    must array; ordering is non-deterministic because the source code iterates
    over a set, so we match by qualifier type.
    """
    assert "bool" in generated_query
    assert "must" in generated_query["bool"]
    must_entries: list[ESEquivalentQualifierPairCollection] = generated_query[
        "bool"
    ]["must"]

    assert len(must_entries) == len(qualifiers)

    entries_by_type: dict[str, ESEquivalentQualifierPairCollection] = {}
    for entry in must_entries:
        types_in_entry = {
            k for term in entry["bool"]["should"] for k in term["term"].keys()
        }
        assert len(types_in_entry) == 1
        entries_by_type[types_in_entry.pop()] = entry

    for qualifier in qualifiers:
        qtype = biolink.rmprefix(qualifier["qualifier_type_id"])
        assert qtype in entries_by_type
        verify_expanded_qualifier(qualifier, entries_by_type[qtype])


def check_single_query_payload(q_graph: QueryGraphDict, generated_payload: ESPayload):
    assert generated_payload is not None

    query_content = generated_payload["query"]["bool"]
    filter_content = query_content["filter"]
    assert filter_content is not None
    assert isinstance(filter_content, list)

    q_edge = next(iter(q_graph["edges"].values()), None)
    side_type = Literal["object", "subject"]
    sides: list[side_type] = ["subject", "object"]

    # qualifier checker (post-expansion format)
    # 0. > 1 constraints       -> top-level `should` + `minimum_should_match: 1`
    # 1. 1 constraint, >1 qual -> `ESBoolQueryForExpandedQualifiers` flattened into `filter`
    # 2. 1 constraint, 1 qual  -> single `ESEquivalentQualifierPairCollection` appended to `filter`

    if q_edge.get("qualifier_constraints"):
        qualifier_entries: list[QualifierConstraintDict] = q_edge[
            "qualifier_constraints"
        ]

        if len(qualifier_entries) > 1:
            assert "should" in query_content
            assert query_content.get("minimum_should_match") == 1

            should_array = query_content["should"]
            assert len(should_array) == len(qualifier_entries)

            for qualifier_entry, generated_query in zip(
                qualifier_entries, should_array
            ):
                qualifiers = qualifier_entry["qualifier_set"]
                if len(qualifiers) == 1:
                    verify_expanded_qualifier(qualifiers[0], generated_query)
                elif len(qualifiers) > 1:
                    verify_expanded_multi_qualifiers(qualifiers, generated_query)
        else:
            # single constraint: qualifier expansion entries are in `filter`
            qualifiers = qualifier_entries[0]["qualifier_set"]
            bool_entries = [clause for clause in filter_content if "bool" in clause]
            assert len(bool_entries) == len(qualifiers)

            entries_by_type: dict[str, dict] = {}
            for entry in bool_entries:
                types_in_entry = {
                    k
                    for term in entry["bool"]["should"]
                    for k in term["term"].keys()
                }
                assert len(types_in_entry) == 1
                entries_by_type[types_in_entry.pop()] = entry

            for qualifier in qualifiers:
                qtype = biolink.rmprefix(qualifier["qualifier_type_id"])
                assert qtype in entries_by_type
                verify_expanded_qualifier(qualifier, entries_by_type[qtype])

    # hacky attribute checking for now
    if q_edge.get("attribute_constraints"):
        assert "must" in query_content
        must = query_content["must"]
        assert must == [
            {"range": {"has_total": {"gt": 2}}},
            {"range": {"has_total": {"lte": 4}}},
        ]

    for _side in sides:
        node = q_graph["nodes"][q_edge[_side]]
        if node.get("constraints"):
            assert "must" in query_content
            assert "must_not" in query_content

            must = query_content["must"]
            assert must == [
                {"term": {f"{_side}.chembl_natural_product": True}}
            ]

            must_not = query_content["must_not"]
            assert must_not == [
                {"term": {f"{_side}.chembl_prodrug": False}}
            ]

    # generate check targets
    required_fields_to_check = dict()
    # Generated field targets
    # {'predicate_ancestors': ['causes'], 'object.id.keyword': ['UMLS:C0011847'], 'subject.category': ['Gene'], 'object.category': ['Disease']}

    for field in EDGE_FIELDS_MAPPING.keys():
        if field in q_edge:
            required_fields_to_check[EDGE_FIELDS_MAPPING[field]] = (
                remove_biolink_prefixes(q_edge[field])
            )


    def add_to_required_fields(_field: str, _side: side_type):
        cur_node = q_graph["nodes"][q_edge[_side]]
        if _field in cur_node:
            if _field != 'categories' or "ids" not in cur_node:
                required_fields_to_check[f"{_side}.{NODE_FIELDS_MAPPING[_field]}"] = (
                    remove_biolink_prefixes(cur_node[_field])
                )

    for field in NODE_FIELDS_MAPPING.keys():
        for side in sides:
            add_to_required_fields(field, side)


    for single_filter in filter_content:
        if "terms" not in single_filter:
            continue

        terms = single_filter["terms"]

        for term in terms.keys():
            if term in required_fields_to_check:
                assert terms[term] == required_fields_to_check[term]
                required_fields_to_check.pop(term)

    assert not required_fields_to_check

def test_bypass_payload(
        es_transpiler: ElasticsearchTranspiler
) -> None:
    # generated_payload = es_transpiler.convert_triple(ID_BYPASS_PAYLOAD)

    generated_payload = _convert_triple(es_transpiler, ID_BYPASS_PAYLOAD)
    check_single_query_payload(ID_BYPASS_PAYLOAD, generated_payload)
    must_clauses = generated_payload["query"]["bool"]["filter"]

    # make sure id is present
    assert any(
        clause.get("terms", {}).get("subject.id") is not None
        for clause in must_clauses
    )

    # make sure category is NOT present
    assert not any(
        "subject.category" in clause.get("terms", {})
        for clause in must_clauses
    )

@pytest.mark.parametrize(
    "q_graph",
    [SINGLE_EXPANDED_QUALIFIER_QGRAPH, EXPANDED_QUALIFIER_QGRAPH],
    ids=["single_qualifier", "multi_qualifier"],
)
def test_expanded_qualifier_constraints(
    q_graph: QueryGraphDict,
    es_transpiler: ElasticsearchTranspiler,
) -> None:
    """Each (type, value) pair in a qualifier_set should expand into a
    `bool.should` clause containing the original pair plus all biolink
    descendants. The single-qualifier case exercises the
    `"should" in qualifier_terms["bool"]` branch in `generate_queries`
    (bare `ESEquivalentQualifierPairCollection` appended to filter); the
    multi-qualifier case exercises the `"must" in qualifier_terms["bool"]`
    branch (entries extended from `ESBoolQueryForExpandedQualifiers`).
    """
    generated_payload = _convert_triple(es_transpiler, q_graph)

    assert generated_payload is not None
    query_content = generated_payload["query"]["bool"]
    filter_content = query_content["filter"]

    # Only a single qualifier_constraints entry -> no top-level should/minimum_should_match
    assert "should" not in query_content
    assert "minimum_should_match" not in query_content

    q_edge = q_graph["edges"]["e0"]
    qualifiers = q_edge["qualifier_constraints"][0]["qualifier_set"]

    # Collect the bool-wrapped expansion entries (each qualifier becomes one)
    expansion_entries = [clause for clause in filter_content if "bool" in clause]
    assert len(expansion_entries) == len(qualifiers)

    # Index expansions by the qualifier type embedded in the should-terms
    expansions_by_type: dict[str, list[ESTermClause]] = {}
    for entry in expansion_entries:
        inner = entry["bool"]
        assert "should" in inner
        assert inner.get("minimum_should_match") == 1

        should_terms = inner["should"]
        assert len(should_terms) >= 1

        types_in_should = {next(iter(term["term"].keys())) for term in should_terms}
        # All terms in a single expansion are for the same qualifier type
        assert len(types_in_should) == 1
        expansions_by_type[types_in_should.pop()] = should_terms

    # Every input qualifier must have a matching expansion containing the original value
    for qualifier in qualifiers:
        qtype = biolink.rmprefix(qualifier["qualifier_type_id"])
        qvalue = biolink.rmprefix(qualifier["qualifier_value"])
        assert qtype in expansions_by_type, (
            f"Expected expansion for qualifier type {qtype}"
        )

        values = {next(iter(term["term"].values())) for term in expansions_by_type[qtype]}
        assert qvalue in values, (
            f"Expected original value {qvalue} to be retained among the "
            f"descendants for {qtype}, got {values}"
        )

    # Standard term filters for the subject/object ids and predicate should still be present
    term_fields = {
        next(iter(clause["terms"].keys()))
        for clause in filter_content
        if "terms" in clause
    }
    assert {"subject.id", "object.id", "predicate_ancestors"}.issubset(term_fields)


@pytest.mark.parametrize(*Q_GRAPH_CASES, ids=Q_GRAPH_CASES_IDS)
def test_convert_triple(
    q_graph: QueryGraphDict, es_transpiler: ElasticsearchTranspiler
) -> None:
    # generated_payload = es_transpiler.convert_triple(q_graph)
    generated_payload = _convert_triple(es_transpiler, q_graph)
    check_single_query_payload(q_graph, generated_payload)


@pytest.mark.parametrize(*Q_GRAPH_CASES, ids=Q_GRAPH_CASES_IDS)
def test_convert_batch_triple(
    q_graph: QueryGraphDict, es_transpiler: ElasticsearchTranspiler
) -> None:
    batch_q_graphs = [q_graph for i in range(10)]

    # generated_payload_list = es_transpiler.convert_batch_triple(batch_q_graphs)
    generated_payload_list = _convert_batch_triple(es_transpiler, batch_q_graphs)
    for generated_payload in generated_payload_list:
        check_single_query_payload(q_graph, generated_payload)


@pytest.mark.asyncio
async def test_convert_results(es_transpiler: ElasticsearchTranspiler):
    result = es_transpiler.convert_results(BASE_QGRAPH, SIMPLE_ES_HITS)

    assert result is not None


@pytest.mark.asyncio
async def test_convert_batch_results(es_transpiler: ElasticsearchTranspiler):
    results = es_transpiler.convert_batch_results([BASE_QGRAPH], [SIMPLE_ES_HITS])

    for result in results:
        assert result is not None
