---
config:
  environments:
    local:
      target: http://localhost:3000
      http:
        timeout: 300
      phases:
        - duration: 1
          maxVusers: 20
          arrivalCount: 20
          name: Concurrency test
    dev:
      target: http://api.bte.ncats.io
      http:
        timeout: 300
      phases:
        - duration: 1
          maxVusers: 20
          arrivalCount: 20
          name: Concurrency test
  payload:
    path: creative_examples.csv
    fields: [input_id]
  processor: functions.js
