---
# Default configuration
instance_env: dev
log_level: debug
host: 0.0.0.0
port: 8080
workers:  # Number of workers, unset to use n_cpus
worker_concurrency: 10  # Number of concurrent tasks per worker
allow_profiler: true  # Allow all queries to enable profiling with a query parameter
job:
  timeout: -1  # Time in seconds before a job should time out, set to -1 to disable
  ttl: 2592000  # Time in seconds for a job to remain after it was last touched
  ttl_max: 31536000  # Time in seconds for a job to remain, regardless of last touch
log:
  log_to_mongo: true  # Persist jobs in MongoDB
  ttl: 1209600  # time in seconds for logs to be kept
redis:
  cluster: false
  host: localhost
  port: 6379
  password:
  ssl_enabled: false
  attempts: 3  # Number of attempts to accomplish operation before considering it failed
mongo:
  host: localhost
  port: 27017
  username:
  password:
  authsource:
  attempts: 3  # Number of attempts to accomplish operation before considering it failed
  shutdown_timeout: 3  # Time in seconds to wait for serialize task to finish
  flood_batch_size: 1000  # Batch size for basic mongo inserts
tier0:
  neo4j:
    query_timeout: 1600  # Time in seconds before a neo4j query should time out
    connect_retries: 25  # Number of retries before declaring a connection failure
    host: ""
    bolt_port: 7687
    username: ""
    password: ""
    database_name: neo4j
telemetry:
  otel_enabled: false
  otel_host: jaeger-otel-collector.sri
  otel_port: 4318
  otel_trace_endpoint: /v1/traces
  sentry_enabled: false  # Implies otel_enabled
  sentry_dsn:
  traces_sample_rate: 0.1
  profiles_sample_rate: 1.0
