---
# Note that any attribute name that would usually contain dashes
# instead contains underscores
# e.g. x-translator is x_translator
# This is due to some pydantic weirdness, but is correct in the output.
description: Translator Knowledge Provider
version: 0.0.1
title: Retriever
contact:
  email: jcallaghan@scripps.edu
  name: Jackson Callaghan
  url: https://github.com/tokebe
  x_id: tokebe
  x_role: responsible developer
license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html
termsOfService: https://biothings.io/about
tags:
  - {name: meta_knowledge_graph}
  - {name: query}
  - {name: asyncquery}
  - {name: asyncquery_status}
  - {name: translator}
  - {name: trapi}
  - {name: biothings}
x_translator:
  component: KP
  team: [BioPack]
  biolink-version: 4.2.1  # Retriever acquires the appropriate biolink release
  infores: biopack-retriever
  externalDocs:
    description: >-
      The values for component and team are restricted according to this external
      JSON schema. See schema and examples at url
    url: https://github.com/NCATSTranslator/translator_extensions/blob/production/x-translator/
x_trapi:
  version: 1.5.0
  muticuriequery: false
  pathfinderquery: false
  asyncquery: true
  operations: [lookup]
  batch_size_limit: 300
  rate_limit: 300
  test_data_location:
    default:
      # TODO test data & location
      url: https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/biothings_explorer/sri-test-bte-ara.json
  externalDocs:
    description: >-
      The values for version are restricted according to the regex in this external
      JSON schema. See schema and examples at url
    url: https://github.com/NCATSTranslator/translator_extensions/blob/production/x-trapi/
response_descriptions:
  meta_knowledge_graph:
    '200': >-
      Returns meta knowledge graph representation of this TRAPI web service.
  query:
    '200': >-
      OK. There may or may not be results. Note that some of the provided
      identifiers may not have been recognized.
    '400': >-
      Bad request. The request is invalid according to this OpenAPI
      schema OR a specific identifier is believed to be invalid somehow
      (not just unrecognized).
    '413': >-
      Payload too large. Indicates that batch size was over the limit
      specified in x-trapi.
    '429': >-
      Payload too large. Indicates that batch size was over the limit
      specified in x-trapi.
  asyncquery:
    '200': >-
      The query is accepted for processing and the Response will be
      sent to the callback url when complete.
  asyncquery_status:
    '200': >-
      Returns the status and current logs of a previously
      submitted asyncquery.
    '404': job_id not found
    '501': >-
      Return code 501 indicates that this endpoint has not been
      implemented at this site. Sites that implement /asyncquery
      MUST implement /asyncquery_status/{job_id}, but those that
      do not implement /asyncquery SHOULD NOT implement
      /asyncquery_status.
  asyncquery_response:
    '200': >-
      Returns either the status and logs, or if complete, the complete response  of a previously
      submitted asyncquery.
  logs:
    '200': Logs in either flat or structured JSON format.
    '404': Indicates this service is disabled by config.
