name: deploy to dev server

on:
  pull_request:
    branches:
      - development
    types: [ closed ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_DEV }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd opt/BioThings_Explorer_TRAPI
          git stash && git pull
          npm i --production
          pm2 restart all

  performance-test:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and run performance test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_DEV }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd opt/BioThings_Explorer_TRAPI/performance-test
          artillery run -e dev --output report_dev.json --config config.yaml scenarios/query.yaml
          artillery report --output report.html report_dev.json
          pm2 restart all